grid_storage_url = "https://yoursasurl"
grid_password = ""
oracle_password = ""
root_password = ""
ora_sys_password = ""
ora_system_password = ""
ora_monitor_password = ""
oracle_database_name = "testdb"
